#include "Common.ush"
#include "/Engine/Generated/Material.ush"
#include "/Engine/Generated/VertexFactory.ush"

struct FSimpleMeshPassVSToPS
{
	FVertexFactoryInterpolantsVSToPS FactoryInterpolants;
	float4 SvPosition : SV_POSITION;
};


float3 InputColor;

void MainVS(
	FVertexFactoryInput Input,
	out FSimpleMeshPassVSToPS Output)
{
	ResolvedView = ResolveView();// view

	FVertexFactoryIntermediates VFIntermediates = GetVertexFactoryIntermediates(Input);
	
	float4 PosWS = VertexFactoryGetWorldPosition(Input, VFIntermediates);
	float3 NormalWS = VertexFactoryGetWorldNormal(Input, VFIntermediates);

	// TBN matrix local
	float3x3 TangentToLocal = VertexFactoryGetTangentToLocal(Input, VFIntermediates);

	FMaterialVertexParameters VertexParameters = GetMaterialVertexParameters(Input, VFIntermediates, PosWS.xyz, TangentToLocal);
	PosWS.xyz += GetMaterialWorldPositionOffset(VertexParameters);
	
	float4 RasterizedWorldPosition = VertexFactoryGetRasterizedWorldPosition(Input, VFIntermediates, PosWS);

	Output.FactoryInterpolants = VertexFactoryGetInterpolantsVSToPS(Input, VFIntermediates, VertexParameters);
	// vertex position in clip space
	Output.SvPosition = mul(RasterizedWorldPosition, ResolvedView.TranslatedWorldToClip);
}

void MainPS(
	FSimpleMeshPassVSToPS In,
	out float4 OutColor1 : SV_Target0,
	out float4 OutColor2 : SV_Target1,
	out float4 OutColor3 : SV_Target2)
{
	float3 Color1 = float3(1.0, 0.0, 0.0);
	float3 Color2 = float3(0.0, 1.0, 0.0);
	float3 Color3 = float3(0.0, 0.0, 1.0);
	
	OutColor1 = float4(Color1, 1.0);
	OutColor2 = float4(Color2, 1.0);
	OutColor3 = float4(Color3, 1.0);
}